### ISSUE TITLE
webpage does not load

### ISSUE THREAD

**Issue by 5tigerjelly** [plastic-oceans461/plastic-oceans461.github.io#19]
![image](https://user-images.githubusercontent.com/15973528/40895433-5667de9e-6764-11e8-8847-5a543a90ca4f.png)

Currently using chrome on desktop.
There is no error message on console

**Comment by lisakoss** [comment]
Please visit us here: https://plastic-oceans.herokuapp.com/ Our initial deployment failed, but we just got it working. We'd love it if you could take a time to check us out again! Thank you!

**Comment by 5tigerjelly** [comment]
Thanks!
