### ISSUE TITLE
Avatar is updated but said is invalid

### ISSUE THREAD

**Issue by 5tigerjelly** [plastic-oceans461/plastic-oceans461.github.io#21]
I gave a link to my github profile, the image on the top updated, but on the input field, shows as invalid URL

![image](https://user-images.githubusercontent.com/15973528/40897223-b6a28660-676e-11e8-8bf4-7bf41067a174.png)

**Comment by alexiskoss** [comment]
Just updated our app to check for the content type of image URLs instead of checking for a valid extension. Thanks for catching this!
