### ISSUE TITLE
Profile Edit, username showing as in use when no changes have been made

### ISSUE THREAD

**Issue by johnwjlim** [plastic-oceans461/plastic-oceans461.github.io#29]
Username showing as "already in use" when no changes have been made, which means I have to change my username in order to change anything else. 

![image](https://user-images.githubusercontent.com/34074206/40902023-5c84da3e-6787-11e8-8c62-86fac22e1223.png)

**Comment by lisakoss** [comment]
Closing this because it's already been reported! But thank you!
