### ISSUE TITLE
Question on quiz question

### ISSUE THREAD

**Issue by johnwjlim** [plastic-oceans461/plastic-oceans461.github.io#30]
![image](https://user-images.githubusercontent.com/34074206/40903987-1d8077ec-678e-11e8-9f81-1b3e5b964b34.png)

I believe 3rd world nations and developing nations mean pretty much the same thing. Did you guys mean "developed nations" instead of "developing nations?"

**Comment by JaneQuichocho** [comment]
Nice catch!
