### ISSUE TITLE
Blank Screen in Chrome

### ISSUE THREAD

**Issue by AntonZheng** [plastic-oceans461/plastic-oceans461.github.io#32]
When directed to the [https://plastic-oceans461.github.io/build/](https://plastic-oceans461.github.io/build/) page, I encounter a blank page.

<img width="1307" alt="screen shot 2018-06-04 at 1 06 43 am" src="https://user-images.githubusercontent.com/16981362/40905814-e79b0e0c-6793-11e8-9ffa-8c22eba55e8a.png">

**Comment by lisakoss** [comment]
Please visit here instead: https://plastic-oceans.herokuapp.com The link on the website is the wrong build deployment. Thank you! :)
